use std::fmt::Write as _;

use zed_interfaces::paths::ARCHIVE_ROOT;

use crate::nix_export_plan::NixExportPlan;

use super::LockedNixpkgs;

pub(super) fn render_flake(plan: &NixExportPlan, nixpkgs: &LockedNixpkgs) -> String {
    let systems = plan
        .intent
        .systems
        .iter()
        .map(|system| nix_string(system))
        .collect::<Vec<_>>()
        .join(" ");
    let attribute = nix_string(&plan.intent.attribute);
    let mut out = String::new();
    out.push_str("{\n");
    out.push_str(
        "  description = \"Generated by zed-pkg from an immutable frozen export plan\";\n\n",
    );
    writeln!(
        &mut out,
        "  inputs.nixpkgs.url = {};",
        nix_string(&nixpkgs.reference)
    )
    .expect("writing to String cannot fail");
    out.push_str("\n  outputs = { self, nixpkgs }:\n");
    out.push_str("    let\n");
    writeln!(&mut out, "      systems = [ {systems} ];").expect("writing to String cannot fail");
    out.push_str("      forAllSystems = nixpkgs.lib.genAttrs systems;\n");
    out.push_str("    in\n");
    out.push_str("    {\n");
    out.push_str("      packages = forAllSystems (\n");
    out.push_str("        system:\n");
    out.push_str("        let\n");
    out.push_str("          pkgs = import nixpkgs { inherit system; };\n");
    out.push_str("          package = pkgs.callPackage ./package.nix { };\n");
    out.push_str("        in\n");
    out.push_str("        {\n");
    writeln!(&mut out, "          {attribute} = package;").expect("writing to String cannot fail");
    out.push_str("          default = package;\n");
    out.push_str("        }\n");
    out.push_str("      );\n\n");
    out.push_str("      checks = forAllSystems (system: {\n");
    writeln!(
        &mut out,
        "        package = builtins.getAttr {attribute} self.packages.${{system}};"
    )
    .expect("writing to String cannot fail");
    out.push_str("      });\n");
    out.push_str("    };\n");
    out.push_str("}\n");
    out
}

pub(super) fn render_package(plan: &NixExportPlan, plan_sha256: &str) -> String {
    let payload_root = format!(
        "share/zed-pkg/{}/{}/{}",
        plan.package.org, plan.package.name, plan.package.version
    );
    let mut out = String::new();
    out.push_str("{ stdenvNoCC }:\n\n");
    out.push_str("stdenvNoCC.mkDerivation {\n");
    writeln!(
        &mut out,
        "  pname = {};",
        nix_string(&format!("{}-{}", plan.package.org, plan.package.name))
    )
    .expect("writing to String cannot fail");
    writeln!(
        &mut out,
        "  version = {};",
        nix_string(&plan.package.version)
    )
    .expect("writing to String cannot fail");
    writeln!(&mut out, "  src = ./artifacts/{};", plan.source.file_name)
        .expect("writing to String cannot fail");
    writeln!(&mut out, "  sourceRoot = {};", nix_string(ARCHIVE_ROOT))
        .expect("writing to String cannot fail");
    out.push_str("  outputs = [ \"out\" ];\n");
    out.push_str("  strictDeps = true;\n");
    out.push_str("  dontConfigure = true;\n");
    out.push_str("  dontBuild = true;\n");
    out.push_str("  dontFixup = true;\n");
    out.push_str("  dontStrip = true;\n");
    out.push_str("  dontPatchShebangs = true;\n\n");
    out.push_str("  installPhase = ''\n");
    out.push_str("    runHook preInstall\n");
    writeln!(&mut out, "    payloadRoot=\"$out/{payload_root}\"")
        .expect("writing to String cannot fail");
    out.push_str("    mkdir -p \"$payloadRoot\"\n");
    out.push_str("    cp -R ./. \"$payloadRoot/\"\n");
    if !plan.bins.is_empty() {
        out.push_str("    mkdir -p \"$out/bin\"\n");
        for (name, relative) in &plan.bins {
            writeln!(
                &mut out,
                "    ln -s \"$payloadRoot/{relative}\" \"$out/bin/{name}\""
            )
            .expect("writing to String cannot fail");
        }
    }
    out.push_str("    runHook postInstall\n");
    out.push_str("  '';\n\n");
    out.push_str("  passthru.zed = {\n");
    out.push_str("    schema = \"zed.nix-export-plan/v1\";\n");
    writeln!(&mut out, "    planSha256 = {};", nix_string(plan_sha256))
        .expect("writing to String cannot fail");
    writeln!(
        &mut out,
        "    artifactSha256 = {};",
        nix_string(&plan.source.artifact.sha256)
    )
    .expect("writing to String cannot fail");
    out.push_str("  };\n\n");
    out.push_str("  meta = {\n");
    out.push_str("    description = \"Immutable artifact exported by zed-pkg\";\n");
    out.push_str("    platforms = [");
    for system in &plan.intent.systems {
        write!(&mut out, " {}", nix_string(system)).expect("writing to String cannot fail");
    }
    out.push_str(" ];\n");
    out.push_str("  };\n");
    out.push_str("}\n");
    out
}

pub(super) fn render_readme(
    plan: &NixExportPlan,
    plan_sha256: &str,
    flake_lock_sha256: &str,
) -> String {
    format!(
        "# Generated zed-pkg Nix export\n\n\
This standalone flake was rendered from a frozen `zed.nix-export-plan/v1`. It is unrelated to the Zed text editor.\n\n\
## Immutable inputs\n\n\
- Package: `{}/{}@{}`\n\
- Nix attribute: `{}`\n\
- Systems: `{}`\n\
- Zed artifact SHA-256: `{}`\n\
- Plan SHA-256: `{plan_sha256}`\n\
- `flake.lock` SHA-256: `{flake_lock_sha256}`\n\n\
## Verification\n\n\
```console\n\
nix flake check --offline --no-update-lock-file\n\
nix build --offline --no-update-lock-file '.#{}'\n\
```\n\n\
`metadata/bundle.json` is the canonical, source-redacted inventory. It hashes every generated file except itself. Rendering performs no Nix evaluation, network access, credential lookup, cache publication, or store realization. A final `zed.nix-adapter/v1` record is created only after explicit realization and output verification.\n",
        plan.package.org,
        plan.package.name,
        plan.package.version,
        plan.intent.attribute,
        plan.intent.systems.join(", "),
        plan.source.artifact.sha256,
        plan.intent.attribute,
    )
}

fn nix_string(value: &str) -> String {
    let mut out = String::with_capacity(value.len() + 2);
    out.push('"');
    let mut chars = value.chars().peekable();
    while let Some(ch) = chars.next() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            '$' if chars.peek() == Some(&'{') => out.push_str("\\$"),
            other => out.push(other),
        }
    }
    out.push('"');
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn nix_string_escapes_interpolation_and_control_characters() {
        assert_eq!(nix_string("a${b}\\\"\n"), "\"a\\${b}\\\\\\\"\\n\"");
    }
}
