#!/usr/bin/env python3
"""Apply the DEN-772 Rust Cargo configuration fix exactly once."""

from pathlib import Path

OPS = Path(__file__).resolve().parents[1] / "src" / "ops.rs"
content = OPS.read_text(encoding="utf-8")

helper_anchor = "/// Emit the native wiring file for each adapter that needs one."
if content.count(helper_anchor) != 1:
    raise RuntimeError("expected one toolchain-wiring anchor")
if "struct CargoPatchEntry" in content:
    raise RuntimeError("Cargo patch support is already present")

helpers = r'''#[derive(Debug, Clone, PartialEq, Eq)]
struct CargoPatchEntry {
    package: String,
    config_path: String,
}

fn cargo_package_name(root: &Path) -> Result<Option<String>> {
    let manifest_path = root.join("Cargo.toml");
    if !manifest_path.is_file() {
        return Ok(None);
    }
    let document = fs::read_to_string(&manifest_path)
        .with_context(|| format!("reading {}", manifest_path.display()))?;
    let document: toml::Value = toml::from_str(&document)
        .with_context(|| format!("parsing {}", manifest_path.display()))?;
    let Some(package) = document.get("package") else {
        return Ok(None);
    };
    let package = package
        .as_table()
        .with_context(|| format!("{}: [package] must be a table", manifest_path.display()))?;
    let name = package
        .get("name")
        .and_then(toml::Value::as_str)
        .with_context(|| format!("{}: [package].name is required", manifest_path.display()))?;
    if name.trim().is_empty() {
        bail!("{}: [package].name must not be empty", manifest_path.display());
    }
    Ok(Some(name.to_string()))
}

fn cargo_patch_entries(config_dir: &Path, paths: &[PathBuf]) -> Result<Vec<CargoPatchEntry>> {
    let mut entries: BTreeMap<String, String> = BTreeMap::new();
    for path in paths {
        let Some(package) = cargo_package_name(path)? else {
            eprintln!(
                "warning: {} has no root [package].name; emitting a Cargo paths override without a crates.io patch entry",
                path.display()
            );
            continue;
        };
        let config_path = pathdiff_relative(config_dir, path)
            .to_string_lossy()
            .replace('\\', "/");
        if let Some(existing) = entries.get(&package)
            && existing != &config_path
        {
            bail!(
                "installed Rust crates `{}` and `{}` both declare package name `{package}`; Cargo cannot patch one crate name to two paths",
                existing,
                config_path
            );
        }
        entries.insert(package, config_path);
    }
    Ok(entries
        .into_iter()
        .map(|(package, config_path)| CargoPatchEntry {
            package,
            config_path,
        })
        .collect())
}

fn toml_basic_string(value: &str) -> Result<String> {
    serde_json::to_string(value).context("quoting a generated Cargo configuration string")
}

'''
content = content.replace(helper_anchor, helpers + helper_anchor, 1)

rust_start = content.index("            Adapter::Rust => {")
rust_end = content.index("            Adapter::Dart => {", rust_start)
new_rust_block = r'''            Adapter::Rust => {
                // Cargo's `paths` override can replace a package that already
                // participates in resolution, but it cannot introduce an
                // unpublished crate by itself. Pair it with config-level
                // `[patch.crates-io]` entries so a normal version dependency can
                // resolve to the installed Zed crate without touching the
                // consumer's Cargo.toml.
                let mut config_paths: Vec<String> = paths
                    .iter()
                    .map(|path| {
                        pathdiff_relative(&zed_dir, path)
                            .to_string_lossy()
                            .replace('\\', "/")
                    })
                    .collect();
                config_paths.sort();
                config_paths.dedup();
                let patches = cargo_patch_entries(&zed_dir, paths)?;

                let mut doc = String::from(
                    "# Generated by `zed install`. Use this config directly with:\n\
                     #\n\
                     #   cargo --config .zed/cargo-paths.toml build\n\
                     #\n\
                     # or copy/merge it into .cargo/config.toml. Paths are\n\
                     # relative to the config file; .zed and .cargo are siblings.\n",
                );
                doc.push_str("paths = [\n");
                for path in &config_paths {
                    doc.push_str(&format!("    {},\n", toml_basic_string(path)?));
                }
                doc.push_str("]\n");
                if !patches.is_empty() {
                    doc.push_str("\n[patch.crates-io]\n");
                    for patch in &patches {
                        doc.push_str(&format!(
                            "{} = {{ path = {} }}\n",
                            toml_basic_string(&patch.package)?,
                            toml_basic_string(&patch.config_path)?,
                        ));
                    }
                }
                let path = zed_dir.join("cargo-paths.toml");
                fs::write(&path, doc)?;
                println!(
                    "wrote {} ({} crate(s)); use with `cargo --config .zed/cargo-paths.toml ...` or merge into .cargo/config.toml",
                    path.display(),
                    config_paths.len()
                );
            }
'''
content = content[:rust_start] + new_rust_block + content[rust_end:]

unit_test_anchor = '''    #[test]
    fn lock_only_frozen_restore_skips_only_the_missing_manifest_comparison() {
'''
if content.count(unit_test_anchor) != 1:
    raise RuntimeError("expected one frozen-lock test anchor")
unit_tests = r'''    #[test]
    fn rust_cargo_config_introduces_an_unpublished_crate_by_package_name() {
        let temp = tempfile::tempdir().unwrap();
        let project = temp.path().join("consumer");
        let package = project.join("zed_modules/acme/tool");
        fs::create_dir_all(&package).unwrap();
        fs::write(
            package.join("Cargo.toml"),
            r#"[package]
name = "tool-crate"
version = "1.2.3"
edition = "2021"
"#,
        )
        .unwrap();
        let roots = BTreeMap::from([(Adapter::Rust, vec![package])]);

        write_toolchain_wiring(&project, &roots).unwrap();

        let generated = fs::read_to_string(project.join(".zed/cargo-paths.toml")).unwrap();
        let parsed: toml::Value = toml::from_str(&generated).unwrap();
        assert_eq!(
            parsed["paths"][0].as_str(),
            Some("../zed_modules/acme/tool")
        );
        assert_eq!(
            parsed["patch"]["crates-io"]["tool-crate"]["path"].as_str(),
            Some("../zed_modules/acme/tool")
        );
        assert!(generated.contains("cargo --config .zed/cargo-paths.toml"));
    }

    #[test]
    fn rust_cargo_config_rejects_two_paths_for_one_crate_name() {
        let temp = tempfile::tempdir().unwrap();
        let project = temp.path().join("consumer");
        let first = project.join("zed_modules/acme/first");
        let second = project.join("zed_modules/acme/second");
        for package in [&first, &second] {
            fs::create_dir_all(package).unwrap();
            fs::write(
                package.join("Cargo.toml"),
                r#"[package]
name = "duplicate-crate"
version = "1.0.0"
"#,
            )
            .unwrap();
        }
        let roots = BTreeMap::from([(Adapter::Rust, vec![first, second])]);

        let error = write_toolchain_wiring(&project, &roots)
            .unwrap_err()
            .to_string();
        assert!(error.contains("duplicate-crate"), "{error}");
        assert!(error.contains("two paths"), "{error}");
    }

'''
content = content.replace(unit_test_anchor, unit_tests + unit_test_anchor, 1)
OPS.write_text(content, encoding="utf-8")
print("DEN-772 Rust Cargo configuration fixed")
