#!/usr/bin/env python3
"""Correct generated Cargo fragment paths for .cargo/config.toml."""

from pathlib import Path

OPS = Path(__file__).resolve().parents[1] / "src" / "ops.rs"
content = OPS.read_text(encoding="utf-8")

replacements = [
    (
        "fn cargo_patch_entries(config_dir: &Path, paths: &[PathBuf]) -> Result<Vec<CargoPatchEntry>> {",
        "fn cargo_patch_entries(project: &Path, paths: &[PathBuf]) -> Result<Vec<CargoPatchEntry>> {",
    ),
    (
        '''        let config_path = pathdiff_relative(config_dir, path)
            .to_string_lossy()
            .replace('\\\\', "/");''',
        '''        let config_path = relative_to(project, path);''',
    ),
    (
        '''                let mut config_paths: Vec<String> = paths
                    .iter()
                    .map(|path| {
                        pathdiff_relative(&zed_dir, path)
                            .to_string_lossy()
                            .replace('\\\\', "/")
                    })
                    .collect();''',
        '''                let mut config_paths: Vec<String> =
                    paths.iter().map(|path| relative_to(project, path)).collect();''',
    ),
    (
        "                let patches = cargo_patch_entries(&zed_dir, paths)?;",
        "                let patches = cargo_patch_entries(project, paths)?;",
    ),
    (
        '''                let mut doc = String::from(
                    "# Generated by `zed install`. Use this config directly with:\\n\\
                     #\\n\\
                     #   cargo --config .zed/cargo-paths.toml build\\n\\
                     #\\n\\
                     # or copy/merge it into .cargo/config.toml. Paths are\\n\\
                     # relative to the config file; .zed and .cargo are siblings.\\n",
                );''',
        '''                let mut doc = String::from(
                    "# Generated by `zed install` for this project root.\\n\\
                     # Copy or merge this fragment into .cargo/config.toml.\\n\\
                     # The consumer's Cargo.toml remains unchanged.\\n",
                );''',
    ),
    (
        '''                    "wrote {} ({} crate(s)); use with `cargo --config .zed/cargo-paths.toml ...` or merge into .cargo/config.toml",''',
        '''                    "wrote {} ({} crate(s)); copy or merge into .cargo/config.toml",''',
    ),
    (
        '            Some("../zed_modules/acme/tool")',
        '            Some("zed_modules/acme/tool")',
    ),
    (
        '        assert!(generated.contains("cargo --config .zed/cargo-paths.toml"));',
        '        assert!(generated.contains("merge this fragment into .cargo/config.toml"));',
    ),
]

for old, new in replacements:
    count = content.count(old)
    expected = 2 if old == '            Some("../zed_modules/acme/tool")' else 1
    if count != expected:
        raise RuntimeError(f"expected {expected} copies of replacement target, found {count}: {old[:80]!r}")
    content = content.replace(old, new)

OPS.write_text(content, encoding="utf-8")
print("DEN-772 Cargo project-root paths corrected")
