//! Manifest-authoritative VCS source composition.
//!
//! .zpkg.toml owns source intent. Native VCS metadata such as .gitmodules is
//! generated compatibility state or migration input, never a parallel package
//! graph authority.

use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use anyhow::{Context, Result, bail};
use serde::Deserialize;
use zed_interfaces::vcs::Vcs;
use zed_interfaces::paths::MANIFEST_FILE;

use crate::config::read_manifest;
use crate::transaction::ProjectTransaction;

const GENERATED_GITMODULES_HEADER: &str =
    "# Generated by zed from .zpkg.toml. Do not edit directly; run `zed workspace sync`.\n";
const DEFAULT_CHECKOUT_DIR: &str = ".zed/vcs";
const DEFAULT_SUBMODULE_DIR: &str = "submodules";
const MAX_MANIFEST_BYTES: u64 = 4 * 1024 * 1024;

#[derive(Debug, Clone, Default, Deserialize)]
#[serde(default)]
struct ManifestEnvelope {
    interop: InteropEnvelope,
}

#[derive(Debug, Clone, Default, Deserialize)]
#[serde(default)]
struct InteropEnvelope {
    #[serde(rename = "source-composition", alias = "source_composition")]
    source_composition: SourceComposition,
}

#[derive(Debug, Clone, Default, Deserialize)]
#[serde(default)]
struct SourceComposition {
    checkout_dir: Option<String>,
    git_submodule_dir: Option<String>,
    sources: BTreeMap<String, SourceEntry>,
}

#[derive(Debug, Clone, Deserialize)]
struct SourceEntry {
    #[serde(default)]
    vcs: Vcs,
    url: String,
    role: String,
    #[serde(default)]
    projection: Projection,
    path: Option<String>,
    package: Option<String>,
    revision: Option<String>,
    branch: Option<String>,
    #[serde(default)]
    recursive: bool,
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Deserialize)]
#[serde(rename_all = "kebab-case")]
enum Projection {
    #[default]
    Checkout,
    GitSubmodule,
}

#[derive(Debug, Clone)]
struct ResolvedSource {
    name: String,
    vcs: Vcs,
    url: String,
    projection: Projection,
    role: String,
    package: Option<String>,
    path: String,
    revision: Option<String>,
    branch: Option<String>,
    recursive: bool,
}

#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct SyncReport {
    pub sources: usize,
    pub git_submodules: usize,
    pub checkouts: usize,
}

fn run(dir: &Path, program: &str, args: &[&str]) -> Result<String> {
    let output = Command::new(program)
        .args(args)
        .current_dir(dir)
        .env("GIT_TERMINAL_PROMPT", "0")
        .env("HGPLAIN", "1")
        .env("PAGER", "cat")
        .output()
        .with_context(|| format!("failed to run `{program}` (is it installed?)"))?;
    if !output.status.success() {
        bail!(
            "`{program} {}` failed: {}",
            args.join(" "),
            String::from_utf8_lossy(&output.stderr).trim()
        );
    }
    Ok(String::from_utf8_lossy(&output.stdout).trim().to_string())
}

fn read_raw(project: &Path) -> Result<SourceComposition> {
    let path = project.join(MANIFEST_FILE);
    let metadata = fs::symlink_metadata(&path)
        .with_context(|| format!("inspecting {}", path.display()))?;
    if !metadata.file_type().is_file() {
        bail!("{} must be a regular file", path.display());
    }
    if metadata.len() > MAX_MANIFEST_BYTES {
        bail!("{} exceeds the {MAX_MANIFEST_BYTES}-byte manifest limit", path.display());
    }
    let text = fs::read_to_string(&path).with_context(|| format!("reading {}", path.display()))?;
    let envelope: ManifestEnvelope =
        toml::from_str(&text).with_context(|| format!("parsing {}", path.display()))?;
    Ok(envelope.interop.source_composition)
}

pub fn find_root(requested: &Path) -> Result<Option<PathBuf>> {
    for candidate in requested.ancestors() {
        let manifest = candidate.join(MANIFEST_FILE);
        if !manifest.exists() {
            continue;
        }
        if !read_raw(candidate)?.sources.is_empty() {
            return Ok(Some(candidate.to_path_buf()));
        }
    }
    Ok(None)
}

pub fn manifest_declares_sources(requested: &Path) -> Result<bool> {
    Ok(find_root(requested)?.is_some())
}

fn validate_name(name: &str) -> Result<()> {
    if name.is_empty()
        || name.len() > 128
        || name.starts_with('.')
        || !name
            .bytes()
            .all(|b| b.is_ascii_alphanumeric() || matches!(b, b'.' | b'_' | b'-'))
    {
        bail!(
            "source name `{name}` must use 1-128 characters from [A-Za-z0-9._-] and may not start with a dot"
        );
    }
    Ok(())
}

fn validate_safe_relative(path: &str, field: &str) -> Result<()> {
    let p = Path::new(path);
    if path.trim().is_empty()
        || p.is_absolute()
        || path.contains('\\')
        || p.components().any(|component| {
            matches!(
                component,
                std::path::Component::ParentDir
                    | std::path::Component::RootDir
                    | std::path::Component::Prefix(_)
            )
        })
    {
        bail!("{field} `{path}` must be a safe project-relative path");
    }
    Ok(())
}

fn normalize(path: &str) -> &str {
    path.trim().trim_matches('/')
}

fn paths_overlap(left: &str, right: &str) -> bool {
    let left = normalize(left);
    let right = normalize(right);
    left == right
        || left
            .strip_prefix(right)
            .is_some_and(|suffix| suffix.starts_with('/'))
        || right
            .strip_prefix(left)
            .is_some_and(|suffix| suffix.starts_with('/'))
}

fn is_reserved_source_path(path: &str) -> bool {
    let normalized = normalize(path);
    let first = normalized.split('/').next().unwrap_or_default();
    matches!(first, ".git" | ".hg" | ".svn" | ".zpkg-staging")
        || matches!(normalized, ".zpkg.toml" | ".zpkg.lock" | ".gitmodules")
        || paths_overlap(normalized, ".zed/operation.lock")
}

fn is_allowed_repo_url(url: &str) -> bool {
    !url.chars().any(char::is_whitespace)
        && (["https://", "http://", "ssh://", "git://", "git+ssh://"]
            .iter()
            .any(|scheme| url.starts_with(scheme))
            || (url.contains('@') && url.contains(':') && !url.contains("://")))
}

fn validate_scalar(value: &str, field: &str, source: &str) -> Result<()> {
    if value.trim().is_empty()
        || value.len() > 512
        || value.starts_with('-')
        || value.chars().any(char::is_control)
        || value.chars().any(char::is_whitespace)
    {
        bail!(
            "source `{source}` {field} must be a non-option VCS token <= 512 bytes without whitespace or control characters"
        );
    }
    Ok(())
}

fn resolve(project: &Path) -> Result<Vec<ResolvedSource>> {
    let raw = read_raw(project)?;
    let checkout_root = raw
        .checkout_dir
        .as_deref()
        .map(str::trim)
        .filter(|v| !v.is_empty())
        .unwrap_or(DEFAULT_CHECKOUT_DIR);
    let submodule_root = raw
        .git_submodule_dir
        .as_deref()
        .map(str::trim)
        .filter(|v| !v.is_empty())
        .unwrap_or(DEFAULT_SUBMODULE_DIR);
    validate_safe_relative(checkout_root, "checkout_dir")?;
    validate_safe_relative(submodule_root, "git_submodule_dir")?;
    if is_reserved_source_path(checkout_root) || is_reserved_source_path(submodule_root) {
        bail!("source-composition roots may not target VCS metadata or Zed transaction state");
    }
    if paths_overlap(checkout_root, submodule_root) {
        bail!(
            "source-composition checkout_dir `{checkout_root}` and git_submodule_dir `{submodule_root}` must be disjoint"
        );
    }

    let manifest = read_manifest(project)?;
    let modules_dir = manifest.modules_dir();
    for (field, value) in [
        ("checkout_dir", checkout_root),
        ("git_submodule_dir", submodule_root),
    ] {
        if paths_overlap(value, modules_dir) {
            bail!(
                "source-composition {field} `{value}` overlaps Zed package install directory `{modules_dir}`"
            );
        }
    }

    let mut paths = BTreeMap::<String, String>::new();
    let mut out = Vec::with_capacity(raw.sources.len());
    for (name, source) in raw.sources {
        validate_name(&name)?;
        if !is_allowed_repo_url(&source.url) || source.url.chars().any(char::is_control) {
            bail!("source `{name}` has an invalid repository URL");
        }
        validate_scalar(&source.role, "role", &name)?;
        if !matches!(
            source.role.as_str(),
            "workspace" | "inventory" | "embedded-source" | "experiment-reference" | "legacy"
        ) {
            bail!("source `{name}` has unsupported role `{}`", source.role);
        }
        if source.projection == Projection::GitSubmodule && source.vcs != Vcs::Git {
            bail!("source `{name}` uses git-submodule projection but vcs is {}", source.vcs);
        }
        if source.role == "workspace" && source.package.is_none() {
            bail!("workspace source `{name}` must declare package = \"org/name\"");
        }
        if let Some(package) = source.package.as_deref() {
            crate::ops::split_key(package)?;
        }
        if source.revision.is_some() && source.branch.is_some() {
            bail!("source `{name}` may declare revision or branch, not both");
        }
        if source.projection == Projection::GitSubmodule && source.revision.is_some() {
            bail!(
                "Git-submodule source `{name}` may not declare revision; the superproject gitlink owns the exact commit"
            );
        }
        if let Some(revision) = source.revision.as_deref() {
            validate_scalar(revision, "revision", &name)?;
        }
        if let Some(branch) = source.branch.as_deref() {
            validate_scalar(branch, "branch", &name)?;
        }

        let path = source.path.unwrap_or_else(|| {
            let root = if source.projection == Projection::GitSubmodule {
                submodule_root
            } else {
                checkout_root
            };
            format!("{root}/{name}")
        });
        validate_safe_relative(&path, "source path")?;
        if is_reserved_source_path(&path) {
            bail!("source `{name}` path `{path}` targets reserved VCS or Zed state");
        }
        if paths_overlap(&path, modules_dir) {
            bail!(
                "source `{name}` path `{path}` overlaps Zed package install directory `{modules_dir}`"
            );
        }
        if let Some((previous_path, previous_name)) = paths
            .iter()
            .find(|(previous_path, _)| paths_overlap(previous_path, &path))
        {
            bail!(
                "source `{name}` path `{path}` overlaps source `{previous_name}` path `{previous_path}`"
            );
        }
        paths.insert(path.clone(), name.clone());
        out.push(ResolvedSource {
            name,
            vcs: source.vcs,
            url: source.url,
            projection: source.projection,
            role: source.role,
            package: source.package,
            path,
            revision: source.revision,
            branch: source.branch,
            recursive: source.recursive,
        });
    }
    out.sort_by(|a, b| a.name.cmp(&b.name));
    Ok(out)
}

fn git_config_quote(value: &str) -> Result<String> {
    if value.is_empty() || value.chars().any(char::is_control) {
        bail!("Git config value must be non-empty and contain no control characters");
    }
    Ok(format!(
        "\"{}\"",
        value.replace('\\', "\\\\").replace('"', "\\\"")
    ))
}

fn render_gitmodules(entries: &[ResolvedSource]) -> Result<String> {
    let mut out = String::from(GENERATED_GITMODULES_HEADER);
    for source in entries
        .iter()
        .filter(|source| source.projection == Projection::GitSubmodule)
    {
        let section = format!("zed:{}", source.name);
        out.push_str(&format!(
            "\n[submodule {}]\n\tpath = {}\n\turl = {}\n",
            git_config_quote(&section)?,
            git_config_quote(&source.path)?,
            git_config_quote(&source.url)?,
        ));
        if let Some(branch) = source.branch.as_deref() {
            out.push_str(&format!("\tbranch = {}\n", git_config_quote(branch)?));
        }
    }
    Ok(out)
}

fn generated_gitmodules(project: &Path) -> Result<bool> {
    let path = project.join(".gitmodules");
    match fs::read_to_string(&path) {
        Ok(text) => Ok(text.starts_with(GENERATED_GITMODULES_HEADER)),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(false),
        Err(error) => Err(error).with_context(|| format!("reading {}", path.display())),
    }
}

fn write_gitmodules(project: &Path, entries: &[ResolvedSource]) -> Result<()> {
    let path = project.join(".gitmodules");
    let rendered = render_gitmodules(entries)?;
    let current = fs::read_to_string(&path).ok();
    if current.as_deref() == Some(rendered.as_str()) {
        return Ok(());
    }
    let mut transaction = ProjectTransaction::begin(project)?;
    transaction.backup(&path)?;
    fs::write(&path, rendered).with_context(|| format!("writing {}", path.display()))?;
    transaction.commit()
}

fn gitlink_exists(project: &Path, path: &str) -> Result<bool> {
    let output = run(project, "git", &["ls-files", "--stage", "--", path])?;
    Ok(output.lines().any(|line| line.starts_with("160000 ")))
}

fn sync_git_submodules(project: &Path, sources: &[ResolvedSource]) -> Result<usize> {
    let entries: Vec<_> = sources
        .iter()
        .filter(|source| source.projection == Projection::GitSubmodule)
        .collect();
    if entries.is_empty() {
        return Ok(0);
    }
    run(project, "git", &["rev-parse", "--show-toplevel"])
        .context("git-submodule projections require a Git superproject")?;

    // Existing authored .gitmodules must be migrated explicitly. Generated
    // files are disposable projections and are rewritten deterministically.
    if project.join(".gitmodules").exists() && !generated_gitmodules(project)? {
        bail!(
            "authored .gitmodules conflicts with manifest-authoritative source composition; run `zed overtake --git-submodules` first"
        );
    }

    for source in &entries {
        let child = project.join(&source.path);
        let has_gitlink = gitlink_exists(project, &source.path)?;
        if !has_gitlink {
            if child.exists() {
                bail!(
                    "source `{}` path {} already exists but is not a Git gitlink; refusing to take ownership",
                    source.name,
                    child.display()
                );
            }
            let name = format!("zed:{}", source.name);
            let mut owned = vec!["submodule".to_string(), "add".to_string()];
            if let Some(branch) = source.branch.as_deref() {
                owned.extend(["-b".to_string(), branch.to_string()]);
            }
            owned.extend([
                "--name".to_string(),
                name,
                source.url.clone(),
                source.path.clone(),
            ]);
            let refs: Vec<&str> = owned.iter().map(String::as_str).collect();
            run(project, "git", &refs)?;
        }
    }

    write_gitmodules(project, sources)?;
    run(project, "git", &["add", "--", ".gitmodules"])?;
    run(project, "git", &["submodule", "sync", "--recursive"])?;
    for source in &entries {
        let name = format!("submodule.zed:{}.url", source.name);
        run(project, "git", &["config", "--local", &name, &source.url])?;
        let mut update = vec![
            "submodule",
            "update",
            "--init",
            "--checkout",
        ];
        if source.recursive {
            update.push("--recursive");
        }
        update.extend(["--", source.path.as_str()]);
        run(project, "git", &update)?;
        verify_gitlink_checkout(project, source)?;
    }
    Ok(entries.len())
}

fn verify_gitlink_checkout(project: &Path, source: &ResolvedSource) -> Result<()> {
    let expected = run(
        project,
        "git",
        &["rev-parse", &format!("HEAD:{}", source.path)],
    )?;
    let actual = run(&project.join(&source.path), "git", &["rev-parse", "HEAD"])?;
    if expected != actual {
        bail!(
            "Git submodule source `{}` is at {actual}, expected superproject gitlink {expected}",
            source.name
        );
    }
    Ok(())
}

fn sync_git_submodules_frozen(project: &Path, sources: &[ResolvedSource]) -> Result<usize> {
    let entries: Vec<_> = sources
        .iter()
        .filter(|source| source.projection == Projection::GitSubmodule)
        .collect();
    if entries.is_empty() {
        return Ok(0);
    }
    run(project, "git", &["rev-parse", "--show-toplevel"])
        .context("Git-submodule projections require a Git superproject")?;

    let expected_projection = render_gitmodules(sources)?;
    let path = project.join(".gitmodules");
    let current = fs::read_to_string(&path).with_context(|| {
        format!(
            "--frozen source composition requires the generated {} to already exist",
            path.display()
        )
    })?;
    if current != expected_projection || !current.starts_with(GENERATED_GITMODULES_HEADER) {
        bail!(
            "--frozen source composition refuses missing, authored, or drifted .gitmodules; run `zed workspace sync` and commit the projection first"
        );
    }

    for source in &entries {
        if !gitlink_exists(project, &source.path)? {
            bail!(
                "--frozen source composition requires committed Git gitlink `{}` for source `{}`",
                source.path,
                source.name
            );
        }
    }

    run(project, "git", &["submodule", "sync", "--recursive"])?;
    for source in &entries {
        let name = format!("submodule.zed:{}.url", source.name);
        run(project, "git", &["config", "--local", &name, &source.url])?;
        let mut update = vec!["submodule", "update", "--init", "--checkout"];
        if source.recursive {
            update.push("--recursive");
        }
        update.extend(["--", source.path.as_str()]);
        run(project, "git", &update)?;
        verify_gitlink_checkout(project, source)?;
    }
    Ok(entries.len())
}

fn is_clean(vcs: Vcs, path: &Path) -> Result<bool> {
    match vcs {
        Vcs::Git | Vcs::Jj | Vcs::Sapling => {
            Ok(run(path, "git", &["status", "--porcelain"])?.is_empty())
        }
        Vcs::Hg => Ok(run(path, "hg", &["status", "-q"])?.is_empty()),
        Vcs::Fossil => Ok(run(path, "fossil", &["changes"])?.is_empty()),
        Vcs::Pijul => bail!("pijul source sync is not yet implemented"),
    }
}

fn clone_checkout(project: &Path, source: &ResolvedSource) -> Result<()> {
    let path = project.join(&source.path);
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    let dest = path
        .to_str()
        .context("source checkout destination is not valid UTF-8")?;
    match source.vcs {
        Vcs::Git => {
            run(project, "git", &["clone", "--", &source.url, dest])?;
        }
        Vcs::Hg => {
            run(project, "hg", &["clone", "--", &source.url, dest])?;
        }
        Vcs::Jj => {
            run(project, "jj", &["git", "clone", "--", &source.url, dest])?;
        }
        Vcs::Sapling => {
            run(project, "sl", &["clone", "--", &source.url, dest])?;
        }
        Vcs::Fossil => bail!(
            "fossil source checkout is declared but automated clone is not certified yet"
        ),
        Vcs::Pijul => bail!(
            "pijul source checkout is declared but automated clone is not certified yet"
        ),
    }
    Ok(())
}

fn sync_checkout(project: &Path, source: &ResolvedSource) -> Result<()> {
    let path = project.join(&source.path);
    if !path.exists() {
        clone_checkout(project, source)?;
    }
    if !path.is_dir() {
        bail!("source `{}` path {} is not a directory", source.name, path.display());
    }
    if !is_clean(source.vcs, &path)? {
        bail!(
            "source `{}` at {} has local changes; refusing destructive VCS synchronization",
            source.name,
            path.display()
        );
    }

    match source.vcs {
        Vcs::Git | Vcs::Jj | Vcs::Sapling => {
            let remote = run(&path, "git", &["remote", "get-url", "origin"])?;
            if remote != source.url {
                bail!(
                    "source `{}` origin is `{remote}`, manifest requires `{}`",
                    source.name,
                    source.url
                );
            }
            run(&path, "git", &["fetch", "--prune", "origin"])?;
            if let Some(revision) = source.revision.as_deref() {
                run(&path, "git", &["checkout", "--detach", revision])?;
            } else if let Some(branch) = source.branch.as_deref() {
                run(&path, "git", &["checkout", "--", branch])?;
                run(&path, "git", &["merge", "--ff-only", &format!("origin/{branch}")])?;
            }
        }
        Vcs::Hg => {
            let remote = run(&path, "hg", &["paths", "default"])?;
            if remote != source.url {
                bail!(
                    "source `{}` default Mercurial path is `{remote}`, manifest requires `{}`",
                    source.name,
                    source.url
                );
            }
            run(&path, "hg", &["pull"])?;
            if let Some(revision) = source.revision.as_deref() {
                run(&path, "hg", &["update", "-r", revision])?;
            } else if let Some(branch) = source.branch.as_deref() {
                run(&path, "hg", &["update", branch])?;
            }
        }
        Vcs::Fossil | Vcs::Pijul => {
            bail!("source sync for {} is not certified yet", source.vcs);
        }
    }
    Ok(())
}

pub(crate) fn workspace_members(project: &Path) -> Result<BTreeMap<String, PathBuf>> {
    let canonical_project = fs::canonicalize(project)
        .with_context(|| format!("canonicalizing source-composition root {}", project.display()))?;
    let mut members = BTreeMap::new();
    for source in resolve(project)?
        .into_iter()
        .filter(|source| source.role == "workspace")
    {
        let package = source
            .package
            .as_deref()
            .context("workspace source lost its required package identity")?;
        let root = project.join(&source.path);
        let canonical = fs::canonicalize(&root).with_context(|| {
            format!(
                "workspace source `{}` has not been synchronized at {}",
                source.name,
                root.display()
            )
        })?;
        if !canonical.starts_with(&canonical_project) {
            bail!(
                "workspace source `{}` resolves outside the project: {}",
                source.name,
                canonical.display()
            );
        }
        let manifest_path = canonical.join(MANIFEST_FILE);
        let metadata = fs::symlink_metadata(&manifest_path)
            .with_context(|| format!("inspecting {}", manifest_path.display()))?;
        if !metadata.file_type().is_file() {
            bail!("workspace source `{}` must contain a regular {MANIFEST_FILE}", source.name);
        }
        let manifest = read_manifest(&canonical)?;
        if manifest.full_name() != package {
            bail!(
                "workspace source `{}` declares package `{package}` but checkout contains `{}`",
                source.name,
                manifest.full_name()
            );
        }
        if let Some(previous) = members.insert(package.to_string(), canonical.clone())
            && previous != canonical
        {
            bail!(
                "workspace package `{package}` is provided by more than one source-composition path"
            );
        }
    }
    Ok(members)
}

pub fn sync(project: &Path) -> Result<SyncReport> {
    let sources = resolve(project)?;
    let git_submodules = sync_git_submodules(project, &sources)?;
    let mut checkouts = 0;
    for source in sources
        .iter()
        .filter(|source| source.projection == Projection::Checkout)
    {
        sync_checkout(project, source)?;
        checkouts += 1;
    }
    Ok(SyncReport {
        sources: sources.len(),
        git_submodules,
        checkouts,
    })
}

pub fn sync_frozen(project: &Path) -> Result<SyncReport> {
    let sources = resolve(project)?;
    let checkout_sources: Vec<_> = sources
        .iter()
        .filter(|source| source.projection == Projection::Checkout)
        .map(|source| source.name.as_str())
        .collect();
    if !checkout_sources.is_empty() {
        bail!(
            "--frozen source composition does not yet have an immutable workspace-source lock for ordinary VCS checkouts ({}); use Git-submodule projections or run a reviewed non-frozen `zed workspace sync`",
            checkout_sources.join(", ")
        );
    }
    let git_submodules = sync_git_submodules_frozen(project, &sources)?;
    Ok(SyncReport {
        sources: sources.len(),
        git_submodules,
        checkouts: 0,
    })
}

#[cfg(test)]
mod tests {
    use std::fs;

    use anyhow::Result;

    use super::{
        Projection, paths_overlap, render_gitmodules, resolve, validate_name, validate_safe_relative,
    };

    fn manifest(source_block: &str) -> String {
        format!(
            r#"[package]
org = "acme"
name = "consumer"
version = "1.0.0"
license = "MIT"

[package.repository]
vcs = "git"
url = "https://github.com/acme/consumer"

[install]
dir = ".zed/pkg"

{source_block}
"#
        )
    }

    #[test]
    fn source_names_and_paths_fail_closed() {
        assert!(validate_name("shared-auth").is_ok());
        assert!(validate_name(".hidden").is_err());
        assert!(validate_name("../escape").is_err());
        assert!(validate_safe_relative(".zed/vcs/lib", "path").is_ok());
        assert!(validate_safe_relative("../lib", "path").is_err());
        assert!(validate_safe_relative("/tmp/lib", "path").is_err());
    }

    #[test]
    fn composition_roots_are_disjoint() {
        assert!(paths_overlap(".zed/pkg", ".zed/pkg/acme/lib"));
        assert!(!paths_overlap(".zed/pkg", ".zed/vcs/lib"));
        assert!(!paths_overlap(".zed/pkg", "submodules/lib"));
    }

    #[test]
    fn manifest_sources_resolve_without_native_vcs_metadata() -> Result<()> {
        let project = tempfile::tempdir()?;
        fs::write(
            project.path().join(".zpkg.toml"),
            manifest(
                r#"[interop.source-composition]
checkout_dir = ".zed/vcs"
git_submodule_dir = "submodules"

[interop.source-composition.sources.hg-lib]
vcs = "hg"
url = "https://example.invalid/hg/lib"
role = "inventory"

[interop.source-composition.sources.git-lib]
vcs = "git"
url = "https://github.com/acme/lib.git"
role = "workspace"
projection = "git-submodule"
path = "apps/lib"
package = "acme/lib"
branch = "main"
recursive = true"#,
            ),
        )?;
        let sources = resolve(project.path())?;
        assert_eq!(sources.len(), 2);
        assert_eq!(sources[0].name, "git-lib");
        assert_eq!(sources[0].projection, Projection::GitSubmodule);
        assert_eq!(sources[0].path, "apps/lib");
        assert_eq!(sources[1].path, ".zed/vcs/hg-lib");

        let projection = render_gitmodules(&sources)?;
        assert!(projection.starts_with("# Generated by zed from .zpkg.toml."));
        assert!(projection.contains("[submodule \"zed:git-lib\"]"));
        assert!(projection.contains("path = \"apps/lib\""));
        assert!(!projection.contains("hg-lib"));
        Ok(())
    }

    #[test]
    fn rejects_overlapping_and_cross_vcs_submodule_sources() -> Result<()> {
        for block in [
            r#"[interop.source-composition.sources.bad]
vcs = "git"
url = "https://github.com/acme/bad.git"
role = "inventory"
path = ".zed/pkg/acme/bad""#,
            r#"[interop.source-composition.sources.bad]
vcs = "hg"
url = "https://example.invalid/hg/bad"
role = "inventory"
projection = "git-submodule""#,
        ] {
            let project = tempfile::tempdir()?;
            fs::write(project.path().join(".zpkg.toml"), manifest(block))?;
            assert!(resolve(project.path()).is_err(), "{block}");
        }
        Ok(())
    }
}
