//! Manifest-authoritative source composition for independently editable repositories.
//!
//! `.zpkg.toml` owns source identity and placement. Git's `.gitmodules` is an
//! optional deterministic compatibility projection for sources explicitly
//! declared with `mode = "git-submodule"`.

use std::fs;
use std::path::{Path, PathBuf};
use std::process::{Command, Output};

use anyhow::{Context, Result, bail};
use zed_interfaces::manifest::{Manifest, WorkspaceSourceMode};
use zed_interfaces::paths::MANIFEST_FILE;
use zed_interfaces::vcs::Vcs;

use crate::config::read_manifest;

const GENERATED_HEADER: &str = "# Generated by zed from .zpkg.toml.\n# Do not edit directly; run `zed workspace sync`.\n";

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SyncReport {
    pub root: PathBuf,
    pub git_submodules: usize,
    pub checkouts: usize,
}

pub fn sync(requested: &Path) -> Result<SyncReport> {
    let root = find_workspace_root(requested)?;
    crate::project_lock::with_lock(&root, "sync workspace sources", || {
        crate::transaction::recover_pending(&root)?;
        sync_locked(&root)
    })
}

pub fn has_declared_sources(requested: &Path) -> Result<bool> {
    let requested = requested
        .canonicalize()
        .with_context(|| format!("canonicalizing {}", requested.display()))?;
    for candidate in requested.ancestors() {
        if !candidate.join(MANIFEST_FILE).is_file() {
            continue;
        }
        let manifest = read_manifest(candidate)?;
        if let Some(workspace) = manifest.workspace.as_ref() {
            return Ok(!workspace.sources.is_empty());
        }
    }
    Ok(false)
}

fn find_workspace_root(requested: &Path) -> Result<PathBuf> {
    let requested = requested
        .canonicalize()
        .with_context(|| format!("canonicalizing {}", requested.display()))?;
    for candidate in requested.ancestors() {
        let manifest_path = candidate.join(MANIFEST_FILE);
        if !manifest_path.is_file() {
            continue;
        }
        let manifest = read_manifest(candidate)?;
        if manifest.workspace.is_some() {
            return Ok(candidate.to_path_buf());
        }
    }
    bail!(
        "`zed workspace sync` requires a {MANIFEST_FILE} with a [workspace] section at or above {}",
        requested.display()
    )
}

fn sync_locked(root: &Path) -> Result<SyncReport> {
    let manifest = read_manifest(root)?;
    let workspace = manifest
        .workspace
        .as_ref()
        .context("workspace disappeared after project lock acquisition")?;

    preflight_generated_gitmodules(root, &manifest)?;

    let mut git_submodules = 0usize;
    let mut checkouts = 0usize;
    for (name, source) in &workspace.sources {
        let relative = workspace.source_path(name, source);
        let target = root.join(&relative);
        match source.mode {
            WorkspaceSourceMode::GitSubmodule => {
                sync_git_submodule(root, name, source, &relative, &target)?;
                git_submodules += 1;
            }
            WorkspaceSourceMode::Checkout => {
                sync_checkout(root, name, source, &target)?;
                checkouts += 1;
            }
        }
    }

    if git_submodules > 0 {
        write_generated_gitmodules(root, &manifest)?;
        checked_git(root, &["submodule", "sync", "--recursive"])?;
        checked_git(
            root,
            &["submodule", "update", "--init", "--recursive", "--checkout"],
        )?;
    }

    Ok(SyncReport {
        root: root.to_path_buf(),
        git_submodules,
        checkouts,
    })
}

fn preflight_generated_gitmodules(root: &Path, manifest: &Manifest) -> Result<()> {
    let needs_projection = manifest
        .workspace
        .as_ref()
        .is_some_and(|workspace| {
            workspace
                .sources
                .values()
                .any(|source| source.mode == WorkspaceSourceMode::GitSubmodule)
        });
    if !needs_projection {
        return Ok(());
    }

    let path = root.join(".gitmodules");
    let metadata = match fs::symlink_metadata(&path) {
        Ok(metadata) => metadata,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => return Ok(()),
        Err(error) => return Err(error).with_context(|| format!("inspecting {}", path.display())),
    };
    if !metadata.file_type().is_file() {
        bail!("{} must be a regular file before Zed can project Git submodules", path.display());
    }
    let text = fs::read_to_string(&path).with_context(|| format!("reading {}", path.display()))?;
    if !text.starts_with(GENERATED_HEADER) {
        bail!(
            "{} is human-authored; import/classify it first with `zed overtake --git-submodules` instead of overwriting it",
            path.display()
        );
    }
    Ok(())
}

fn render_gitmodules(manifest: &Manifest) -> Result<String> {
    let Some(workspace) = manifest.workspace.as_ref() else {
        return Ok(GENERATED_HEADER.to_string());
    };
    let mut out = String::from(GENERATED_HEADER);
    for (name, source) in &workspace.sources {
        if source.mode != WorkspaceSourceMode::GitSubmodule {
            continue;
        }
        let path = workspace.source_path(name, source);
        out.push('\n');
        out.push_str(&format!("[submodule \"{name}\"]\n"));
        out.push_str(&format!("\tpath = {path}\n"));
        out.push_str(&format!("\turl = {}\n", source.url));
        if let Some(branch) = source.branch.as_deref() {
            out.push_str(&format!("\tbranch = {branch}\n"));
        }
    }
    Ok(out)
}

fn write_generated_gitmodules(root: &Path, manifest: &Manifest) -> Result<()> {
    let path = root.join(".gitmodules");
    let rendered = render_gitmodules(manifest)?;
    if fs::read_to_string(&path).ok().as_deref() == Some(rendered.as_str()) {
        return Ok(());
    }
    fs::write(&path, rendered).with_context(|| format!("writing {}", path.display()))
}

fn sync_git_submodule(
    root: &Path,
    name: &str,
    source: &zed_interfaces::manifest::WorkspaceSourceSection,
    relative: &str,
    target: &Path,
) -> Result<()> {
    if !matches!(source.vcs, Vcs::Git | Vcs::Jj | Vcs::Sapling) {
        bail!("workspace source `{name}` is not Git-compatible");
    }

    match gitlink_in_index(root, relative)? {
        Some(true) => {}
        Some(false) => bail!(
            "workspace source `{name}` targets `{relative}`, but that path is tracked as an ordinary file/directory instead of a Git submodule"
        ),
        None => {
            if target.exists() {
                bail!(
                    "workspace source `{name}` needs a new Git submodule at {}, but the path already exists; move it aside or import it explicitly",
                    target.display()
                );
            }
            let mut args = vec!["submodule", "add", "--name", name];
            if let Some(branch) = source.branch.as_deref() {
                args.extend(["--branch", branch]);
            }
            args.extend([source.url.as_str(), relative]);
            checked_git(root, &args)?;
        }
    }

    checked_git(root, &["config", "--local", &format!("submodule.{name}.url"), &source.url])?;
    checked_git(root, &["config", "--local", &format!("submodule.{name}.active"), "true"])?;
    if let Some(branch) = source.branch.as_deref() {
        checked_git(root, &["config", "--local", &format!("submodule.{name}.branch"), branch])?;
    }
    Ok(())
}

fn gitlink_in_index(root: &Path, relative: &str) -> Result<Option<bool>> {
    let output = git_output(root, &["ls-files", "--stage", "--", relative])?;
    if !output.status.success() {
        return git_failure(root, &["ls-files", "--stage", "--", relative], output);
    }
    let text = String::from_utf8(output.stdout).context("Git index output is not UTF-8")?;
    let line = text.lines().find(|line| !line.trim().is_empty());
    Ok(line.map(|line| line.starts_with("160000 ")))
}

fn sync_checkout(
    root: &Path,
    name: &str,
    source: &zed_interfaces::manifest::WorkspaceSourceSection,
    target: &Path,
) -> Result<()> {
    match source.vcs {
        Vcs::Git | Vcs::Jj | Vcs::Sapling => sync_git_checkout(root, name, source, target),
        Vcs::Hg => sync_hg_checkout(root, name, source, target),
        Vcs::Fossil | Vcs::Pijul => bail!(
            "workspace checkout transport `{}` for source `{name}` is not implemented yet",
            source.vcs
        ),
    }
}

fn sync_git_checkout(
    root: &Path,
    name: &str,
    source: &zed_interfaces::manifest::WorkspaceSourceSection,
    target: &Path,
) -> Result<()> {
    if !target.exists() {
        create_parent(target)?;
        let target_text = path_arg(target)?;
        let mut args = vec!["clone"];
        if let Some(branch) = source.branch.as_deref() {
            args.extend(["--branch", branch]);
        }
        args.extend([source.url.as_str(), target_text.as_str()]);
        checked_git(root, &args)?;
        return Ok(());
    }
    if !target.join(".git").exists() {
        bail!("workspace source `{name}` exists at {} but is not a Git checkout", target.display());
    }
    let actual = git_line(target, &["remote", "get-url", "origin"])?;
    if actual != source.url {
        bail!(
            "workspace source `{name}` origin mismatch at {}: manifest declares `{}`, checkout has `{actual}`",
            target.display(),
            source.url
        );
    }
    checked_git(target, &["fetch", "--all", "--prune"])?;
    if let Some(branch) = source.branch.as_deref() {
        checked_git(target, &["checkout", branch])?;
        checked_git(target, &["merge", "--ff-only", &format!("origin/{branch}")])?;
    }
    Ok(())
}

fn sync_hg_checkout(
    root: &Path,
    name: &str,
    source: &zed_interfaces::manifest::WorkspaceSourceSection,
    target: &Path,
) -> Result<()> {
    if !target.exists() {
        create_parent(target)?;
        let target_text = path_arg(target)?;
        let mut args = vec!["clone"];
        if let Some(branch) = source.branch.as_deref() {
            args.extend(["-b", branch]);
        }
        args.extend([source.url.as_str(), target_text.as_str()]);
        checked_command(root, "hg", &args)?;
        return Ok(());
    }
    if !target.join(".hg").is_dir() {
        bail!("workspace source `{name}` exists at {} but is not a Mercurial checkout", target.display());
    }
    let actual = command_line(target, "hg", &["paths", "default"])?;
    if actual != source.url {
        bail!(
            "workspace source `{name}` default path mismatch at {}: manifest declares `{}`, checkout has `{actual}`",
            target.display(),
            source.url
        );
    }
    checked_command(target, "hg", &["pull"])?;
    if let Some(branch) = source.branch.as_deref() {
        checked_command(target, "hg", &["update", branch])?;
    }
    Ok(())
}

fn create_parent(target: &Path) -> Result<()> {
    if let Some(parent) = target.parent() {
        fs::create_dir_all(parent).with_context(|| format!("creating {}", parent.display()))?;
    }
    Ok(())
}

fn path_arg(path: &Path) -> Result<String> {
    path.to_str()
        .map(str::to_owned)
        .with_context(|| format!("workspace source path is not UTF-8: {}", path.display()))
}

fn git_line(project: &Path, args: &[&str]) -> Result<String> {
    command_line(project, "git", args)
}

fn command_line(project: &Path, program: &str, args: &[&str]) -> Result<String> {
    let output = command_output(project, program, args)?;
    if !output.status.success() {
        return command_failure(project, program, args, output);
    }
    Ok(String::from_utf8(output.stdout)
        .with_context(|| format!("{program} output is not UTF-8"))?
        .trim()
        .to_string())
}

fn checked_git(project: &Path, args: &[&str]) -> Result<Output> {
    let output = git_output(project, args)?;
    if output.status.success() {
        Ok(output)
    } else {
        git_failure(project, args, output)
    }
}

fn git_output(project: &Path, args: &[&str]) -> Result<Output> {
    let mut command = Command::new("git");
    command.env("GIT_TERMINAL_PROMPT", "0");
    command.args(args).current_dir(project);
    command
        .output()
        .with_context(|| format!("running git {} in {}", args.join(" "), project.display()))
}

fn git_failure<T>(project: &Path, args: &[&str], output: Output) -> Result<T> {
    command_failure(project, "git", args, output)
}

fn checked_command(project: &Path, program: &str, args: &[&str]) -> Result<Output> {
    let output = command_output(project, program, args)?;
    if output.status.success() {
        Ok(output)
    } else {
        command_failure(project, program, args, output)
    }
}

fn command_output(project: &Path, program: &str, args: &[&str]) -> Result<Output> {
    Command::new(program)
        .args(args)
        .current_dir(project)
        .output()
        .with_context(|| format!("running {program} {} in {}", args.join(" "), project.display()))
}

fn command_failure<T>(project: &Path, program: &str, args: &[&str], output: Output) -> Result<T> {
    let stderr = String::from_utf8_lossy(&output.stderr);
    let stderr = stderr.trim();
    let bounded: String = stderr.chars().take(4096).collect();
    bail!(
        "{program} {} failed in {}{}",
        args.join(" "),
        project.display(),
        if bounded.is_empty() {
            String::new()
        } else {
            format!(": {bounded}")
        }
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    fn manifest() -> Manifest {
        Manifest::parse(
            r#"[package]
org = "acme"
name = "root"
version = "1.0.0"

[package.repository]
vcs = "git"
url = "https://github.com/acme/root"

[workspace]

[workspace.sources.api]
vcs = "git"
url = "https://github.com/acme/api"
package = "acme/api"
branch = "main"
mode = "git-submodule"
role = "workspace"
"#,
        )
        .unwrap()
    }

    #[test]
    fn gitmodules_projection_is_deterministic_and_marked_generated() {
        let rendered = render_gitmodules(&manifest()).unwrap();
        assert!(rendered.starts_with(GENERATED_HEADER));
        assert!(rendered.contains("[submodule \"api\"]"));
        assert!(rendered.contains("\tpath = submodules/api"));
        assert!(rendered.contains("\turl = https://github.com/acme/api"));
        assert!(rendered.contains("\tbranch = main"));
    }

    #[test]
    fn generated_projection_never_overwrites_human_gitmodules() {
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join(".gitmodules"), "[submodule \"human\"]\n").unwrap();
        let error = preflight_generated_gitmodules(dir.path(), &manifest()).unwrap_err();
        assert!(error.to_string().contains("human-authored"));
    }
}
