name: ci
on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          path: zed-cli
      - uses: actions/checkout@v4
        with:
          repository: zed-pkg/zed-interfaces
          path: zed-interfaces
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: zed-cli
      - run: cargo fmt --check
        working-directory: zed-cli
      - run: cargo test
        working-directory: zed-cli
